# Generated by Django 4.1.1 on 2023-04-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Registration', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_loan_representativ',
        ),
    ]
