# Generated by Django 4.1.1 on 2023-04-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Registration', '0005_rename_is_staff_user_is_loan_representativ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
